-- MySQL Script generated by MySQL Workbench
-- Mon Jul 19 17:07:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema coupon_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coupon_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coupon_db` DEFAULT CHARACTER SET utf8 ;
USE `coupon_db` ;

-- -----------------------------------------------------
-- Table `coupon_db`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coupon_db`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coupon_db`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coupon_db`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `type_document` VARCHAR(2) NOT NULL,
  `document` INT NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `state` INT NOT NULL,
  `rfid` TEXT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coupon_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coupon_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` LONGTEXT NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coupon_db`.`cupon_kit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coupon_db`.`cupon_kit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `state` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coupon_db`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coupon_db`.`store` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(60) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `state` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coupon_db`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coupon_db`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `image` TEXT NULL,
  `state` TINYINT ZEROFILL NOT NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coupon_db`.`coupon_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coupon_db`.`coupon_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cupon_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coupon_db`.`coupon_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coupon_db`.`coupon_person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  `coupon_product_id` INT NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Data for table `coupon_db`.`rol`
-- -----------------------------------------------------
START TRANSACTION;
USE `coupon_db`;
INSERT INTO `coupon_db`.`rol` (`id`, `name`) VALUES (1, 'administrador');
INSERT INTO `coupon_db`.`rol` (`id`, `name`) VALUES (2, 'cliente');

COMMIT;


-- -----------------------------------------------------
-- Data for table `coupon_db`.`person`
-- -----------------------------------------------------
START TRANSACTION;
USE `coupon_db`;
INSERT INTO `coupon_db`.`person` (`id`, `name`, `lastname`, `type_document`, `document`, `phone`, `state`, `rfid`, `rol_id`) VALUES (1, 'javier ', 'vela', 'cc', 100061440, '3058500461', 1, '0', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `coupon_db`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `coupon_db`;
INSERT INTO `coupon_db`.`user` (`id`, `email`, `password`, `person_id`) VALUES (1, 'admin@rfid.com', 'password', 1);
/* Agregar aqui nuevos usuarios administradores*/
COMMIT;


-- -----------------------------------------------------
-- Data for table `coupon_db`.`store`
-- -----------------------------------------------------
START TRANSACTION;
USE `coupon_db`;
INSERT INTO `coupon_db`.`store` (`id`, `name`, `address`, `phone`, `state`) VALUES (DEFAULT, 'mcdonalds', 'calle 105 - av 35 - 15a', '3058500123', 1);

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
