version: '3.5'
services:
  socket-python:
    build:
      context: ./hardware/socket
    ports:
     - "8089:8089"
    volumes:
      - ./hardware/socket:/hardware/socket
    command: python app.py
  api-python:
    build:
      context: ./api
    ports:
     - "5000:5000"
    volumes:
      - ./api:/api
    depends_on:
      - db
    links: 
      - db 
    command: pymon app.py
  frontend:
    build: 
      context: ./public
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
  db:
    restart: always
    build:
        context: ./docs/sql
        args:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
        - "3306:3306"
volumes:
  mysql:
  mysql_config: