FROM node:14.17 as builder

RUN mkdir /coupon-rfid-angular

WORKDIR /coupon-rfid-angular

# copy the package.json to install dependencies
COPY package.json package-lock.json ./

# Install the dependencies and make the folder
RUN npm install

#RUN npx ngcc --properties es2015 --create-ivy-entry-points

COPY . .

# Build the project and copy the files
RUN npm run ng build -- --prod

# Stage 2
FROM nginx:alpine

COPY ./.server/nginx.conf /etc/nginx/nginx.conf

## Remove default nginx index page
RUN rm -rf /var/www/coupon-rfid-angular/*

# Copy from the stage 1
COPY --from=builder /coupon-rfid-angular/dist/coupon-rfid-angular /var/www/

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]